@echo off
echo Running lint...
call npx pnpm lint > lint.log 2>&1
echo Running typecheck...
call npx pnpm typecheck > tsc.log 2>&1
echo Running build...
call npx pnpm build > build.log 2>&1
echo Done.
